# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: line-works-bot01
  labels:
    app: line-works-bot01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: line-works-bot01
  template:
    metadata:
      labels:
        app: line-works-bot01
    spec:
      containers:
      - name: line-works-bot01
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

